package com.cathay.account.accswitch.dao.domain;

public class AccTestDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_test.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_test.ds
     *
     * @mbg.generated
     */
    private String ds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_test.id
     *
     * @return the value of t_acc_test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_test.id
     *
     * @param id the value for t_acc_test.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_test.content
     *
     * @return the value of t_acc_test.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_test.content
     *
     * @param content the value for t_acc_test.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_test.ds
     *
     * @return the value of t_acc_test.ds
     *
     * @mbg.generated
     */
    public String getDs() {
        return ds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_test.ds
     *
     * @param ds the value for t_acc_test.ds
     *
     * @mbg.generated
     */
    public void setDs(String ds) {
        this.ds = ds == null ? null : ds.trim();
    }
}