package com.cathay.account.accswitch.dao.persistence;

import com.cathay.account.accswitch.dao.domain.AccTestDO;

public interface AccTestDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_test
     *
     * @mbg.generated
     */
    int insert(AccTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_test
     *
     * @mbg.generated
     */
    int insertSelective(AccTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_test
     *
     * @mbg.generated
     */
    AccTestDO selectByPrimaryKey(Integer id);

    AccTestDO selectBycurrentAccDayVO(String accdate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccTestDO record);
}